name: Create VPC Infrastructure
on: 
  workflow_dispatch: 
jobs: 
# DEV-PLAN
  DEV-APPLY:
    runs-on: rhel_arm
    steps: 
      - uses: actions/checkout@v4
      - name: Terraform init 
        run: | 
          
          ls -la 
          # terraform init -backend-config=env-dev/state.tfvars
      - name: Terraform apply 
        run: | 
          # terraform apply -var-file=env-dev/main.tfvars -auto-approve
#QA
# UAT
#PROD