name: Destroy VPC Infrastructure
on: 
  workflow_dispatch: 
jobs: 
  DEV: 
    runs-on: rhel_arm 
    steps: 
      - uses: actions/checkout@v4 
      - name: Destroying VPC Infrastructure 
        run: |
         cd vpc-infra-2-az 
         terraform destroy -var-file=env-dev/main.tfvars -auto-approve
          